FROM golang:alpine AS builder
WORKDIR /app
COPY hello.go .
COPY go.mod .
RUN go build -o fullCycleRocks

FROM scratch
COPY --from=builder /app/fullCycleRocks ./fullCycleRocks
CMD ["./fullCycleRocks"]
